[workspace]
members = [
  "01-inverse-captcha",
  "02-spreadsheet-checksums",
  "03-infinite-memory",
  "04-passphrase",
  "05-jumplist",
  "06-infinite-loop",
  "day7",
  "day8",
  "day9",
  "day10",
  "day11",
  "day12",
  "day13",
  "day14",
  "day15"
]
